(ns hive-mcp.transport
  "Facade for backward compatibility.
   Delegates to hive-mcp.transport.core after tree normalization."
  (:require [hive-mcp.transport.core :as core]))

(def ITransport core/ITransport)
(def IServer core/IServer)
(def connect! core/connect!)
(def disconnect! core/disconnect!)
(def send! core/send!)
(def recv! core/recv!)
(def connected? core/connected?)
(def encode-msg core/encode-msg)
(def decode-msg core/decode-msg)
(def decode-msg-from-stream core/decode-msg-from-stream)
(def unix-transport core/unix-transport)
(def tcp-transport core/tcp-transport)
(def start-unix-server! core/start-unix-server!)
(def start-tcp-server! core/start-tcp-server!)
(def start-server! core/start-server!)
(def stop-server! core/stop-server!)
(def server-running? core/server-running?)
(def broadcast! core/broadcast!)
(def get-clients core/get-clients)
(def client-count core/client-count)
(def get-stream core/get-stream)
